name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe what you'd like.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? Is it related to a frustration?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project does this relate to?
      options:
        - RAG / Search
        - MCP Server
        - CLI
        - Indexing
        - Reasoning
        - Documentation
        - CI / Infrastructure
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other details, screenshots, or examples.
